# Generated by Django 3.0.8 on 2020-07-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200727_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactionstatistic',
            name='user',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='interactionstatistic',
            unique_together={('mechanic', 'user')},
        ),
    ]
