# Generated by Django 3.0.8 on 2020-07-28 13:44

import api.models
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200727_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboard',
            name='users',
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='leadders',
            field=jsonfield.fields.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interactionstatistic',
            name='user',
            field=models.CharField(max_length=255, validators=[api.models.username_exists]),
        ),
    ]
