# Generated by Django 3.0.8 on 2020-07-28 19:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200728_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='sort_by',
            new_name='given_by',
        ),
        migrations.RemoveField(
            model_name='point',
            name='length',
        ),
        migrations.RemoveField(
            model_name='point',
            name='users',
        ),
        migrations.AddField(
            model_name='point',
            name='score',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='point',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.Gamer'),
            preserve_default=False,
        ),
    ]
