# Generated by Django 3.0.8 on 2020-07-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200728_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='user',
            field=models.CharField(default='', max_length=200),
        ),
    ]
