# Generated by Django 3.0.8 on 2020-07-29 21:05

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_auto_20200728_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, validators=[api.models.unique_individual_group]),
        ),
        migrations.AlterField(
            model_name='point',
            name='user',
            field=models.CharField(default='', max_length=200, validators=[api.models.username_exists]),
        ),
        migrations.AlterUniqueTogether(
            name='point',
            unique_together={('user', 'given_by')},
        ),
    ]
