# Generated by Django 3.0.8 on 2020-07-29 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('api', '0008_auto_20200729_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmechanic',
            name='owners',
            field=models.ManyToManyField(to='auth.Group'),
        ),
    ]
