# Generated by Django 3.0.8 on 2020-07-29 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_gmechanic_owners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gmechanic',
            name='owners',
        ),
    ]
