# Generated by Django 3.0.8 on 2020-07-30 17:18

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_gmechanic_owners'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lottery',
            old_name='sort_by',
            new_name='by',
        ),
        migrations.RemoveField(
            model_name='lottery',
            name='length',
        ),
        migrations.RemoveField(
            model_name='lottery',
            name='users',
        ),
        migrations.AddField(
            model_name='lottery',
            name='items',
            field=jsonfield.fields.JSONField(default=list),
        ),
    ]
