# Generated by Django 3.0.8 on 2020-08-01 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200730_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adaptative',
            fields=[
                ('gmechanic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.GMechanic')),
            ],
            bases=('api.gmechanic',),
        ),
    ]
