# Generated by Django 3.0.8 on 2020-08-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_adaptative'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badge',
            old_name='sort_by',
            new_name='by',
        ),
        migrations.AddField(
            model_name='badge',
            name='icon',
            field=models.ImageField(default='', upload_to='badge-icons/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='badge',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='badge',
            name='state',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='badge',
            name='threshold',
            field=models.FloatField(default=99999999),
        ),
        migrations.AlterUniqueTogether(
            name='badge',
            unique_together={('by', 'threshold')},
        ),
        migrations.RemoveField(
            model_name='badge',
            name='length',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='users',
        ),
    ]
