# Generated by Django 3.0.8 on 2020-08-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200812_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unlockable',
            name='length',
        ),
        migrations.RemoveField(
            model_name='unlockable',
            name='sort_by',
        ),
        migrations.RemoveField(
            model_name='unlockable',
            name='users',
        ),
        migrations.AddField(
            model_name='unlockable',
            name='by',
            field=models.CharField(default='score', max_length=100),
        ),
        migrations.AddField(
            model_name='unlockable',
            name='icon',
            field=models.ImageField(default='unlockable_icons/reward.png', upload_to='unlockable_icons'),
        ),
        migrations.AddField(
            model_name='unlockable',
            name='name',
            field=models.CharField(default='Unlockable', max_length=100),
        ),
        migrations.AddField(
            model_name='unlockable',
            name='state',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unlockable',
            name='threshold',
            field=models.FloatField(default=99999999),
        ),
        migrations.AlterField(
            model_name='badge',
            name='by',
            field=models.CharField(default='score', max_length=100),
        ),
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.ImageField(default='badge_icons/reward.png', upload_to='badge_icons'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='name',
            field=models.CharField(default='Badge', max_length=100),
        ),
    ]
