# Generated by Django 3.0.8 on 2020-08-14 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200814_1730'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='unlockable',
            unique_together={('by', 'threshold')},
        ),
    ]
