# Generated by Django 3.0.8 on 2020-08-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200814_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='unlockable',
            name='locked_html',
            field=models.TextField(default=''),
        ),
    ]
