# Generated by Django 3.0.8 on 2020-08-18 10:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20200817_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='easteregg',
            name='length',
        ),
        migrations.RemoveField(
            model_name='easteregg',
            name='sort_by',
        ),
        migrations.RemoveField(
            model_name='easteregg',
            name='users',
        ),
        migrations.AddField(
            model_name='easteregg',
            name='egg_html',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='easteregg',
            name='feedback',
            field=models.ImageField(default='easter_egg_icons/well_done.jpg', upload_to='easter_egg_icons'),
        ),
        migrations.AlterField(
            model_name='level',
            name='max_value',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
