# Generated by Django 3.0.8 on 2020-08-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20200818_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='by',
            field=models.CharField(default='score', max_length=100),
        ),
        migrations.AddField(
            model_name='challenge',
            name='icon',
            field=models.ImageField(default='challenge_icons/challenge.png', upload_to='challenge_icons'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='name',
            field=models.CharField(default='Challenge', max_length=100),
        ),
        migrations.AddField(
            model_name='challenge',
            name='state',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='challenge',
            name='threshold',
            field=models.FloatField(default=99999999),
        ),
        migrations.AlterUniqueTogether(
            name='challenge',
            unique_together={('by', 'threshold')},
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='length',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='sort_by',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='users',
        ),
    ]
