# Generated by Django 3.0.8 on 2020-08-20 15:48

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20200819_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='social_icons/user.jpg', upload_to='social_icons')),
                ('friends', jsonfield.fields.JSONField(default=list)),
            ],
        ),
        migrations.RemoveField(
            model_name='socialnetwork',
            name='length',
        ),
        migrations.RemoveField(
            model_name='socialnetwork',
            name='sort_by',
        ),
        migrations.RemoveField(
            model_name='socialnetwork',
            name='users',
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='messages',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='gamer',
            name='social_profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.SocialProfile'),
            preserve_default=False,
        ),
    ]
