# Generated by Django 3.0.8 on 2020-08-20 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20200820_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamer',
            name='social_profile',
        ),
    ]
