# Generated by Django 3.0.8 on 2020-08-20 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_gamer_social_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamer',
            name='social_profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.SocialProfile'),
            preserve_default=False,
        ),
    ]
