# Generated by Django 3.0.8 on 2020-08-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20200820_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialprofile',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
