# Generated by Django 3.0.8 on 2020-08-24 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20200824_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialprofile',
            old_name='friends',
            new_name='data',
        ),
    ]
