# Generated by Django 3.0.8 on 2020-09-03 14:07

import api.models
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20200826_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialstatus',
            name='length',
        ),
        migrations.RemoveField(
            model_name='socialstatus',
            name='sort_by',
        ),
        migrations.RemoveField(
            model_name='socialstatus',
            name='users',
        ),
        migrations.AddField(
            model_name='socialstatus',
            name='competitiveness',
            field=enumfields.fields.EnumField(default='High', enum=api.models.SocialStatus.CompetitionLevel, max_length=6),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='image',
            field=enumfields.fields.EnumField(default='diamond', enum=api.models.SocialProfile.AvatarType, max_length=11),
        ),
    ]
